version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "5001:5001"
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/app
    depends_on:
      - mongo
    networks:
      - backend
    
  user:
    container_name: user
    build: ./user-service
    ports:
      - "5002:5002"
    env_file:
      - ./user-service/.env
    volumes:
      - ./user-service:/app
    depends_on:
      - mongo
    networks:
      - backend

  appointment:
    build: ./appointment-service
    ports:
      - "5003:5003"
    env_file:
      - ./appointment-service/.env
    volumes:
      - ./appointment-service:/app
    depends_on:
      - mongo
    networks:
      - backend

  notification:
    build: ./notification-service
    ports:
      - "5004:5004"
    env_file:
      - ./notification-service/.env
    volumes:
      - ./notification-service:/app
    depends_on:
      - mongo
    networks:
      - backend


  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:
networks:
  backend:
