version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "5001:5001"
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
